# Generated by Django 4.2.4 on 2023-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="posttag",
            constraint=models.UniqueConstraint(
                fields=("post_id", "tag_id"),
                name="post_tag_unique",
                violation_error_message="Tag already exist for post",
            ),
        ),
    ]
