# Generated by Django 4.2.4 on 2023-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_posttag_post_tag_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
